export const productData = [
  {
    id: 1,
    name: "Cap",
    description: "Stylish summer cap",
    price: 50,
    stock: 25,
    unit: "pcs",
    variant: "Red, Blue, Black",
    category: "Accessories",
    sub_category: "Hats",
  },
  {
    id: 2,
    name: "2 Color T-Shirt",
    description: "Half-sleeve cotton T-shirt",
    price: 20,
    stock: 50,
    unit: "pcs",
    variant: "Black & White",
    category: "Clothing",
    sub_category: "T-Shirts",
  },
  {
    id: 3,
    name: "Polo Tshirt",
    description: "Classic polo t-shirt for men",
    price: 30,
    stock: 40,
    unit: "pcs",
    variant: "Red, Blue",
    category: "Clothing",
    sub_category: "Men's Wear",
  },
  {
    id: 4,
    name: "Couple Set",
    description: "Matching couple outfit",
    price: 80,
    stock: 20,
    unit: "sets",
    variant: "Black & White",
    category: "Clothing",
    sub_category: "Couples Wear",
  },
  {
    id: 5,
    name: "Balt Bag",
    description: "Trendy leather bag",
    price: 100,
    stock: 10,
    unit: "pcs",
    variant: "Brown, Black",
    category: "Accessories",
    sub_category: "Bags",
  },
  {
    id: 6,
    name: "Female Polo T-Shirt",
    description: "Polo T-shirt for women",
    price: 35,
    stock: 60,
    unit: "pcs",
    variant: "Pink, White",
    category: "Clothing",
    sub_category: "Women's Wear",
  },
  {
    id: 7,
    name: "Half Pant",
    description: "Casual summer shorts",
    price: 25,
    stock: 30,
    unit: "pcs",
    variant: "Blue, Black",
    category: "Clothing",
    sub_category: "Bottom Wear",
  },
  {
    id: 8,
    name: "Bag",
    description: "Stylish handbag",
    price: 90,
    stock: 15,
    unit: "pcs",
    variant: "Brown, Blue",
    category: "Accessories",
    sub_category: "Bags",
  },
  {
    id: 9,
    name: "Glasses",
    description: "Trendy sunglasses",
    price: 120,
    stock: 25,
    unit: "pcs",
    variant: "Black, Silver",
    category: "Accessories",
    sub_category: "Glasses",
  },
  {
    id: 10,
    name: "Nike Hat",
    description: "Sports cap by Nike",
    price: 45,
    stock: 12,
    unit: "pcs",
    variant: "Black, Red",
    category: "Accessories",
    sub_category: "Hats",
  },
  {
    id: 11,
    name: "Adidas Shoes",
    description: "Running shoes by Adidas",
    price: 150,
    stock: 20,
    unit: "pairs",
    variant: "White, Black",
    category: "Footwear",
    sub_category: "Shoes",
  },
  {
    id: 12,
    name: "Louis Glasses",
    description: "Luxury sunglasses",
    price: 250,
    stock: 8,
    unit: "pcs",
    variant: "Gold, Black",
    category: "Accessories",
    sub_category: "Glasses",
  },
  {
    id: 13,
    name: "Kids T-Shirt",
    description: "Cotton t-shirt for kids",
    price: 18,
    stock: 40,
    unit: "pcs",
    variant: "Green, Yellow",
    category: "Clothing",
    sub_category: "Kids Wear",
  },
  {
    id: 14,
    name: "Sandals",
    description: "Comfortable summer sandals",
    price: 40,
    stock: 25,
    unit: "pairs",
    variant: "Brown, Black",
    category: "Footwear",
    sub_category: "Sandals",
  },
  {
    id: 15,
    name: "Gucci Bag",
    description: "Luxury handbag by Gucci",
    price: 300,
    stock: 5,
    unit: "pcs",
    variant: "Red, Beige",
    category: "Accessories",
    sub_category: "Bags",
  },
  {
    id: 16,
    name: "Sport Shoes",
    description: "Durable sports shoes",
    price: 130,
    stock: 15,
    unit: "pairs",
    variant: "Blue, White",
    category: "Footwear",
    sub_category: "Shoes",
  },
  {
    id: 17,
    name: "NASA T-Shirt",
    description: "Printed NASA cotton t-shirt",
    price: 35,
    stock: 30,
    unit: "pcs",
    variant: "Black, Grey",
    category: "Clothing",
    sub_category: "T-Shirts",
  },
  {
    id: 18,
    name: "American Pants",
    description: "Comfortable casual pants",
    price: 60,
    stock: 22,
    unit: "pcs",
    variant: "Blue, Black",
    category: "Clothing",
    sub_category: "Pants",
  },
];
